require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'
# source 'https://inmarket-pod-user:****@github.com/ThinkNear/m2mPods.git'
platform :ios, '14.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorApp', :path => '../../node_modules/@capacitor/app'
  pod 'CapacitorFilesystem', :path => '../../node_modules/@capacitor/filesystem'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorKeyboard', :path => '../../node_modules/@capacitor/keyboard'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'CapgoCameraPreview', :path => '../../../capacitor-camera-preview'
  pod 'CapgoCapacitorDataStorageSqlite', :path => '../../../capacitor-data-storage-sqlite'
  pod 'CapgoCapacitorDownloader', :path => '../../node_modules/@capgo/capacitor-downloader'
  pod 'CapgoCapacitorScreenRecorder', :path => '../../../capacitor-screen-recorder'
  pod 'CapgoCapacitorShake', :path => '../../../capacitor-shake'
  pod 'CapgoCapacitorSocialLogin', :path => '../../../capacitor-social-login'
  pod 'CapgoCapacitorUpdater', :path => '../../../capacitor-updater'
  pod 'CapgoCapacitorUploader', :path => '../../../capacitor-uploader'
  pod 'CapgoInappbrowser', :path => '../../../capacitor-inappbrowser'
  pod 'CapgoNativeAudio', :path => '../../../capacitor-native-audio'
  pod 'CapgoNativePurchases', :path => '../../../capacitor-native-purchases'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
