name: Release to capgo

on:
 - workflow_dispatch

jobs:
  build-and-release:
    name: my-job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout CLI repo
        uses: actions/checkout@v4
        with:
          repository: Cap-go/CLI
          path: cli
          ref: bundle_signing
      - name: Setup bun
        uses: oven-sh/setup-bun@v2
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup project for a prod build
        run: |
          sed -i 's|link:@capgo/capacitor-updater|^6.0.0|g' package.json
          mv capacitor.config.ts capacitor.config.ts.tmp
          mv capacitor.config.ts.prod capacitor.config.ts
      - name: Install dependencies
        run: bun install
      - name: Install dependencies (CLI)
        working-directory: ./cli
        run: bun install
      - name: Build CLI
        # env:
        #   CLI_SECRET_URL: ${{ secrets.CLI_SECRET_URL }}
        working-directory: ./cli
        run: bun run build

      - name: Build project
        run: bun run build
      - name: CLI ver
        run: node ./cli/dist/index.js --version

